spring:
  application:
    name: assinaturas

  quartz:
    properties:
      org:
        quartz:
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            isClustered: true
    jdbc:
      initialize-schema: never
    job-store-type: jdbc

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    jdbc-url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver

asaas:
  server-url: https://api-sandbox.asaas.com

aws:
  endpoint-override: ${AWS_ENDPOINT:http://localhost:4566/}
  access-key-id: ${ACCESS_KEY:test}
  secret-access-key: ${ACCESS_SECRET:test}

feign:
  client:
    config:
      default:
        loggerLevel: FULL

access:
  secret: sandbox/asaas/access_token