services:

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-assinaturas
    ports:
      - "5672:5672"
      - "15672:15672"

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=4566
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=${DOCKER_LOCATION}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "./notification.json:/opt/code/localstack/notification.json"
      - "./init-aws.sh:/docker-entrypoint-initaws.d/init-aws.sh"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: assinaturas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  payment-gateway-asaas-mock:
    image: wiremock/wiremock:3.13.2
    container_name: payment-gateway-asaas-mock
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - "--global-response-templating"